name: first demo app

on:
  push:
    branches: [ "main" ]

jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
