name: Node.js test

on:
  push:
    branches: [ "main" ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install all dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Echo all tests passed
        run: echo "All tests passed"
